#! /bin/sh

set -x

mkdir -p config
aclocal -I config

libtoolize --force --automake

autoheader
automake --add-missing --copy
autoconf

[ ! -f mkinstalldirs ] && ln -s config/mkinstalldirs mkinstalldirs
